version: "3.1"
services:
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./.docker/mongo/northwind:/db
      - ./.docker/mongo/northwind:/docker-entrypoint-initdb.d
    ports:
      - 27017:27017
